"""empty message

Revision ID: e5d8cfcbd016
Revises: e7f722ca53e4
Create Date: 2024-09-27 16:58:42.191786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d8cfcbd016'
down_revision = 'e7f722ca53e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends_users',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('friends_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friends_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('users_id', 'friends_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends_users')
    # ### end Alembic commands ###
